#######################################################################################################################
# Voyage API Testing using Cucumber Application
#######################################################################################################################
app:
  name: Voyage API Testing
  contact-support:
    email: support@LighthouseSoftware.com
    phone: 651-888-6021
    website: http://LighthouseSoftware.com/support
  default-country: US

#######################################################################################################################
# Logging
#######################################################################################################################
logging:
  file: voyage-api-testing.log

#######################################################################################################################
# Spring Configuration
#######################################################################################################################
spring:
  application:
    name: Voyage API Testing Cucumber Application
  main:
    banner-mode: "off"

#######################################################################################################################
# Spring Boot Web / Embedded Tomcat
#######################################################################################################################
server:
  port: 8083
  contextPath: /

#######################################################################################################################
# Security
#######################################################################################################################
security:
  ignored: /**

#######################################################################################################################
# Voyage API Testing properties file
#######################################################################################################################
---
voyagestepdef:
  authtypebasic: "Basic"
  applicationcontenttype: application/x-www-form-urlencoded
  applicationacceptjson: application/json
  oauthtokenurl: http://localhost:8080/oauth/token
  tokenname: Voyage SUPER
  clientid: "client_id"
  clientidvalue: client-super
  clientsercret: "client_secret"
  clientsecretvalue: secret
  granttype: "grant_type"
  granttypevalue: client_credentials

voyagestepdefinvalidauthtken:
  accesstoken: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkIjoxNTEwMjMwNDIzOTE4LCJzY29wZSI6WyJSZWFkIERhdGEiLCJXcml0ZSBEYXRhIl0sImV4cCI6MTUxMDIzNzYyMywiYXV0aG9yaXRpZXMiOlsiYXBpLnBlcm1pc3Npb25zLmRlbGV0ZSIsImFwaS5yb2xlcy5kZWxldGUiLCJhcGkucm9sZXMudXBkYXRlIiwiYXBpLnBlcm1pc3Npb25zLmxpc3QiLCJhcGkucGVybWlzc2lvbnMudXBkYXRlIiwiYXBpLnVzZXJzLmNyZWF0ZSIsImFwaS51c2Vycy5nZXQiLCJhcGkudXNlcnMubGlzdCIsImFwaS5wZXJtaXNzaW9ucy5nZXQiLCJhcGkucm9sZXMuZ2V0IiwiYXBpLnVzZXJzLnVwZGF0ZSIsImFwaS5yb2xlcy5jcmVhdGUiLCJhcGkudXNlcnMuZGVsZXRlIiwiYXBpLnBlcm1pc3Npb25zLmNyZWF0ZSIsImFwaS5yb2xlcy5saXN0Il0sImp0aSI6IjM1ZmMzNjM1LWUyNmMtNDUwMi05OTMyLTNmMDhlOTQwZGQzNiIsImNsaWVudF9pZCI6ImNsaWVudC1zdXBlciJ9.gBgsG5lho32ulgOikpr31yMXbM2vQ_MZQUmfPRdAHF8HkuL23qW8cBb-64vBkFGvyvT6OkofmCsBNfnLSfkEHqClaKoOb2wPQhlOnJfLnI7F85zh_SaHTyN1zGPOx3j3EhxCjxir5d8DGVCeqgVB8JoonaTqd5O3-v4xiYplKE0qRQZyuqQuGjeIUOIrhwMfPkyZyZuQs-BhnpidKeDL1fGa5BRtcTXvurbVchz2ex_C4HQgTZe8E7zfloYwBmmKUUi7HPe-zS98U5uBXlLGodXZnM-gkzqvYEMEhPoIIKe_CXnwgEof0b2ENqK8325_KcJ_iirKK3keyJveZmpT3g"
  serviceurlforstatus: "http://localhost:8080/api/status"
  responsemessage: "The remote server returned an error: (401) Unauthorized."
  serviceurlforusers: http://localhost:8080/api/v1/users

cucumberproperties:
  outputdirectory: src/main/resources/static
  outputname: cucumber-results
  sourcefile: src/main/resources/static/cucumber.json

#######################################################################################################################
#
#######################################################################################################################
