#######################################################################################################################
# Voyage API Testing using Cucumber Application
#######################################################################################################################
app:
  name: Voyage API Testing
  contact-support:
    email: support@LighthouseSoftware.com
    phone: 651-888-6021
    website: http://LighthouseSoftware.com/support
  default-country: US

#######################################################################################################################
# Logging
#######################################################################################################################
logging:
  file: voyage-api-testing.log

#######################################################################################################################
# Spring Configuration
#######################################################################################################################
spring:

  application:
    name: Voyage API Testing Cucumber Application

#######################################################################################################################
# Spring Boot Web / Embedded Tomcat
#######################################################################################################################
server:
  port: 8083
  contextPath: /

#######################################################################################################################
# Security
#######################################################################################################################
security:
  ignored: /**
